### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by zoghal** [aziz/virastar#2]
سلام عزیز
نسخه پی اچ پی این پروژه رو آماده نداری؟

**Comment by aziz** [comment]
سلام صالح جان. نه پی اچ پی تو کار من نیست. ولی قراره ورژن جاواسکریپتش رو یکی از بچه‌ها بنویسه. شایدم خودم. به کارت میاد؟

**Comment by zoghal** [comment]
سلام مجدید. آره جاوا بهتر از روبی راحتر میتونم  کانورتش کنم. پس لطفا اوکی شد. ما رو بی خبر نزار.مرسی

**Comment by zoghal** [comment]
عزیز جان واسه جاوا اسکریپت اوکی نشده؟ خبری هست؟

**Comment by TheServat** [comment]
<div dir="rtl">
برای جاوا اسکریپت میتونید از <a href ="https://github.com/juvee/virastar">juvee/virastar</a> و <br>
برای php میتونید از <a href="https://github.com/octoberfa/virastar" >octoberfa/virastar</a> استفاده کنید.
</div>
